// src/mockData.js
export const mockMovies = [
  {
    id: 1,
    title: 'The Shawshank Redemption',
    poster_path: '/9cqXoGbs99pYveDCYp6m6h8P8pU.jpg',
    vote_average: 8.7,
    tagline: "Fear can hold you prisoner. Hope can set you free.",
    release_date: "1994-09-22",
    runtime: 142,
    status: "Released",
    budget: 25000000,
    revenue: 28341469,
    overview: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.",
    genres: [{ name: "Drama" }, { name: "Crime" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Castle Rock Entertainment" }]
  },
  {
    id: 2,
    title: 'The Dark Knight',
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0MZ.jpg',
    vote_average: 8.5,
    tagline: "Welcome to a world without rules.",
    release_date: "2008-07-16",
    runtime: 152,
    status: "Released",
    budget: 185000000,
    revenue: 1004558444,
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.",
    genres: [{ name: "Drama" }, { name: "Action" }, { name: "Crime" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Warner Bros. Pictures" }, { name: "Legendary Pictures" }]
  },
  {
    id: 3,
    title: 'Pulp Fiction',
    poster_path: '/d5iIlFn5s0ImszYzBMXoP8mjlaG.jpg',
    vote_average: 8.5,
    tagline: "Just because you are a character doesn't mean that you have character.",
    release_date: "1994-09-10",
    runtime: 154,
    status: "Released",
    budget: 8000000,
    revenue: 213928762,
    overview: "A burger-loving hit man, his philosophical partner, a drug-addicted gangster's wife and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that weave in and out of each other.",
    genres: [{ name: "Thriller" }, { name: "Crime" }],
    spoken_languages: [{ name: "English" }, { name: "Spanish" }, { name: "French" }],
    production_companies: [{ name: "Miramax" }, { name: "A Band Apart" }]
  },
  {
    id: 4,
    title: 'Forrest Gump',
    poster_path: '/arw2vcBveWOVZr6pxd9XTdQs1T2.jpg',
    vote_average: 8.4,
    tagline: "The world will never be the same once you've seen it through the eyes of Forrest Gump.",
    release_date: "1994-06-23",
    runtime: 142,
    status: "Released",
    budget: 55000000,
    revenue: 677387716,
    overview: "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But through it all, with his innocence and simple-mindedness, he never lost his one true love.",
    genres: [{ name: "Comedy" }, { name: "Drama" }, { name: "Romance" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Paramount Pictures" }]
  },
  {
    id: 5,
    title: 'Inception',
    poster_path: '/edvB211RpfR9yQs4obquA4TUa9W.jpg',
    vote_average: 8.4,
    tagline: "Your mind is the scene of the crime.",
    release_date: "2010-07-15",
    runtime: 148,
    status: "Released",
    budget: 160000000,
    revenue: 825532764,
    overview: "Cobb, a skilled thief who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.",
    genres: [{ name: "Action" }, { name: "Science Fiction" }, { name: "Adventure" }],
    spoken_languages: [{ name: "English" }, { name: "Japanese" }],
    production_companies: [{ name: "Warner Bros. Pictures" }, { name: "Legendary Pictures" }]
  },
  {
    id: 6,
    title: 'Spirited Away',
    poster_path: '/39wmItSpsSSTBzZOCfgHcyQHbsg.jpg',
    vote_average: 8.5,
    tagline: "The tunnel led Chihiro to a mysterious town...",
    release_date: "2001-07-20",
    runtime: 125,
    status: "Released",
    budget: 19000000,
    revenue: 355475245,
    overview: "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    genres: [{ name: "Animation" }, { name: "Family" }, { name: "Fantasy" }],
    spoken_languages: [{ name: "Japanese" }],
    production_companies: [{ name: "Studio Ghibli" }]
  },
  {
    id: 7,
    title: 'Parasite',
    poster_path: '/7IiTTjMvISmB2QvQYdvZbiR9Yv3.jpg',
    vote_average: 8.5,
    tagline: "Act like you own the place.",
    release_date: "2019-05-30",
    runtime: 132,
    status: "Released",
    budget: 11400000,
    revenue: 258762056,
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    genres: [{ name: "Comedy" }, { name: "Thriller" }, { name: "Drama" }],
    spoken_languages: [{ name: "Korean" }],
    production_companies: [{ name: "Barunson E&A" }]
  },
  {
    id: 8,
    title: 'The Matrix',
    poster_path: '/f89U3Y9L9uMBuAW9VEpWyPvDUNo.jpg',
    vote_average: 8.2,
    tagline: "Welcome to the Real World.",
    release_date: "1999-03-31",
    runtime: 136,
    status: "Released",
    budget: 63000000,
    revenue: 463517383,
    overview: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    genres: [{ name: "Action" }, { name: "Science Fiction" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Warner Bros." }, { name: "Village Roadshow Pictures" }]
  },
  {
    id: 9,
    title: 'Interstellar',
    poster_path: '/gEU2QniE6E77NI6vCU6mgS2AWvW.jpg',
    vote_average: 8.4,
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    release_date: "2014-11-05",
    runtime: 169,
    status: "Released",
    budget: 165000000,
    revenue: 701729206,
    overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    genres: [{ name: "Adventure" }, { name: "Drama" }, { name: "Science Fiction" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Legendary Pictures" }, { name: "Syncopy" }]
  },
  {
    id: 10,
    title: 'The Shining',
    poster_path: '/f977m3qH9u77o3gnpS7v1Ssh7yM.jpg',
    vote_average: 8.2,
    tagline: "He came as the caretaker, but this hotel had its own ideas.",
    release_date: "1980-05-23",
    runtime: 146,
    status: "Released",
    budget: 19000000,
    revenue: 44360123,
    overview: "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live through the snow-in for the winter.",
    genres: [{ name: "Horror" }, { name: "Thriller" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Warner Bros." }, { name: "Hawk Films" }]
  },
  {
    id: 11,
    title: 'Toy Story',
    poster_path: '/uXDfjJbdP4ijW5hNpBrjYUBnZ.jpg',
    vote_average: 8.0,
    tagline: "Hang on for the ride of your life!",
    release_date: "1995-10-30",
    runtime: 81,
    status: "Released",
    budget: 30000000,
    revenue: 373554033,
    overview: "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz.",
    genres: [{ name: "Animation" }, { name: "Adventure" }, { name: "Family" }, { name: "Comedy" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Pixar" }]
  },
  {
    id: 12,
    title: 'Get Out',
    poster_path: '/v0edWJ86p55ZpYl0pX0l6p76o6Y.jpg',
    vote_average: 7.6,
    tagline: "Just because you're invited, doesn't mean you're welcome.",
    release_date: "2017-02-24",
    runtime: 104,
    status: "Released",
    budget: 4500000,
    revenue: 255010103,
    overview: "Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family's overly accommodating behavior as nervous attempts to deal with their daughter's interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he could have never imagined.",
    genres: [{ name: "Horror" }, { name: "Mystery" }, { name: "Thriller" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Blumhouse Productions" }]
  },
  {
    id: 13,
    title: 'La La Land',
    poster_path: '/ylXCdC1SdhIeaZpS9S0SmtCNo4K.jpg',
    vote_average: 7.9,
    tagline: "Here's to the fools who dream.",
    release_date: "2016-12-09",
    runtime: 128,
    status: "Released",
    budget: 30000000,
    revenue: 446092357,
    overview: "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.",
    genres: [{ name: "Comedy" }, { name: "Drama" }, { name: "Music" }, { name: "Romance" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Summit Entertainment" }]
  },
  {
    id: 14,
    title: 'Gladiator',
    poster_path: '/ty8vSbi94p9p9p9p9p9p9p9p9p.jpg',
    vote_average: 8.2,
    tagline: "A hero will rise.",
    release_date: "2000-05-01",
    runtime: 155,
    status: "Released",
    budget: 103000000,
    revenue: 460583960,
    overview: "In the year 180, the Death of emperor Marcus Aurelius throws the Roman Empire into chaos. Maximus is one of the Roman army's most capable and trusted generals and a key advisor to the emperor. As Marcus' devious son Commodus ascends to the throne, Maximus is sentenced to death. Maximus escapes, but is captured as a slave and trained as a gladiator, and must fight to the death with other men for the amusement of paying audiences.",
    genres: [{ name: "Action" }, { name: "Adventure" }, { name: "Drama" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Universal Pictures" }, { name: "DreamWorks" }]
  },
  {
    id: 15,
    title: 'Coco',
    poster_path: '/g4y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 8.2,
    tagline: "The celebration of a lifetime.",
    release_date: "2017-10-27",
    runtime: 105,
    status: "Released",
    budget: 175000000,
    revenue: 800526015,
    overview: "Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events.",
    genres: [{ name: "Animation" }, { name: "Family" }, { name: "Music" }, { name: "Adventure" }],
    spoken_languages: [{ name: "English" }, { name: "Spanish" }],
    production_companies: [{ name: "Pixar" }, { name: "Walt Disney Pictures" }]
  },
  {
    id: 16,
    title: 'Se7en',
    poster_path: '/69y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 8.3,
    tagline: "Seven deadly sins. Seven ways to die.",
    release_date: "1995-09-22",
    runtime: 127,
    status: "Released",
    budget: 33000000,
    revenue: 327311859,
    overview: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    genres: [{ name: "Crime" }, { name: "Mystery" }, { name: "Thriller" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "New Line Cinema" }]
  },
  {
    id: 17,
    title: 'Your Name',
    poster_path: '/q7y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 8.5,
    tagline: "I am looking for you, whom I have never met.",
    release_date: "2016-08-26",
    runtime: 106,
    status: "Released",
    budget: 5000000,
    revenue: 357986087,
    overview: "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    genres: [{ name: "Animation" }, { name: "Drama" }, { name: "Romance" }],
    spoken_languages: [{ name: "Japanese" }],
    production_companies: [{ name: "CoMix Wave Films" }]
  },
  {
    id: 18,
    title: 'The Lion King',
    poster_path: '/s9y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 8.3,
    tagline: "Life's greatest adventure is finding your place in the Circle of Life.",
    release_date: "1994-06-23",
    runtime: 89,
    status: "Released",
    budget: 45000000,
    revenue: 763455561,
    overview: "A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah, living by a philosophy: No worries for the rest of your days. But when his past comes to haunt him, the young prince must decide his fate: Will he remain an outcast, or face his demons and become what he needs to be?",
    genres: [{ name: "Animation" }, { name: "Family" }, { name: "Drama" }, { name: "Adventure" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Walt Disney Pictures" }]
  },
  {
    id: 19,
    title: 'Dune',
    poster_path: '/d5y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 7.8,
    tagline: "It begins.",
    release_date: "2021-09-15",
    runtime: 155,
    status: "Released",
    budget: 165000000,
    revenue: 402027830,
    overview: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.",
    genres: [{ name: "Science Fiction" }, { name: "Adventure" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Legendary Pictures" }]
  },
  {
    id: 20,
    title: 'Blade Runner 2049',
    poster_path: '/g9y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 7.5,
    tagline: "There's still a page left.",
    release_date: "2017-10-04",
    runtime: 164,
    status: "Released",
    budget: 150000000,
    revenue: 259239658,
    overview: "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
    genres: [{ name: "Science Fiction" }, { name: "Drama" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Alcon Entertainment" }, { name: "Warner Bros." }]
  },
  {
    id: 21,
    title: 'The Godfather',
    poster_path: '/3bhkrj9m9m9m9m9m9m9m9m9m9.jpg',
    vote_average: 8.7,
    tagline: "An offer you can't refuse.",
    release_date: "1972-03-14",
    runtime: 175,
    status: "Released",
    budget: 6000000,
    revenue: 245066411,
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers.",
    genres: [{ name: "Drama" }, { name: "Crime" }],
    spoken_languages: [{ name: "English" }, { name: "Italian" }],
    production_companies: [{ name: "Paramount Pictures" }]
  },
  {
    id: 22,
    title: 'Fight Club',
    poster_path: '/pB9y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 8.4,
    tagline: "Mischief. Mayhem. Soap.",
    release_date: "1999-10-15",
    runtime: 139,
    status: "Released",
    budget: 63000000,
    revenue: 100853753,
    overview: "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.",
    genres: [{ name: "Drama" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "20th Century Fox" }, { name: "Regency Enterprises" }]
  },
  {
    id: 23,
    title: 'Alien',
    poster_path: '/v9y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 8.1,
    tagline: "In space, no one can hear you scream.",
    release_date: "1979-05-25",
    runtime: 117,
    status: "Released",
    budget: 11000000,
    revenue: 104931801,
    overview: "During its return to Earth, commercial spaceship Nostromo visually intercepts a SOS signal from a distant planet. When a three-member team investigates the source of the signal, they uncover a bizarre lifeform that latches onto one of the crew members.",
    genres: [{ name: "Horror" }, { name: "Science Fiction" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "20th Century Fox" }]
  },
  {
    id: 24,
    title: 'Back to the Future',
    poster_path: '/f9y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 8.3,
    tagline: "He's the only kid ever to get into trouble before he was born.",
    release_date: "1985-07-03",
    runtime: 116,
    status: "Released",
    budget: 19000000,
    revenue: 381109762,
    overview: "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and quickly becoming his mother's new romantic interest. Marty must repair the damage, learn to steer his parents back together, and find a way back to 1985.",
    genres: [{ name: "Adventure" }, { name: "Comedy" }, { name: "Science Fiction" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Universal Pictures" }, { name: "Amblin Entertainment" }]
  },
  {
    id: 25,
    title: 'Leon: The Professional',
    poster_path: '/w9y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 8.3,
    tagline: "If you want a job done right, hire a professional.",
    release_date: "1994-09-14",
    runtime: 110,
    status: "Released",
    budget: 16000000,
    revenue: 46101230,
    overview: "Léon, a top hitman, reluctantly takes in Mathilda, a 12-year-old girl, after her family is murdered by corrupt DEA agents. Léon begins to teach the girl his trade, while she plans her revenge.",
    genres: [{ name: "Action" }, { name: "Crime" }, { name: "Drama" }],
    spoken_languages: [{ name: "English" }, { name: "French" }],
    production_companies: [{ name: "Gaumont" }]
  },
  {
    id: 26,
    title: 'Whiplash',
    poster_path: '/x9y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 8.4,
    tagline: "The road to greatness can take you to the edge.",
    release_date: "2014-10-10",
    runtime: 107,
    status: "Released",
    budget: 3300000,
    revenue: 48982041,
    overview: "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
    genres: [{ name: "Drama" }, { name: "Music" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Blumhouse Productions" }]
  },
  {
    id: 27,
    title: 'Spider-Man: Into the Spider-Verse',
    poster_path: '/z9y9y9y9y9y9y9y9y9y9y9y9y.jpg',
    vote_average: 8.4,
    tagline: "More than one wears the mask.",
    release_date: "2018-12-06",
    runtime: 117,
    status: "Released",
    budget: 90000000,
    revenue: 375540831,
    overview: "Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson \"Kingpin\" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.",
    genres: [{ name: "Animation" }, { name: "Action" }, { name: "Adventure" }, { name: "Science Fiction" }],
    spoken_languages: [{ name: "English" }, { name: "Spanish" }],
    production_companies: [{ name: "Sony Pictures Animation" }, { name: "Marvel Entertainment" }]
  },
  {
    id: 28,
    title: 'Joker',
    poster_path: '/udSbi94p9p9p9p9p9p9p9p9p9p.jpg',
    vote_average: 8.2,
    tagline: "Put on a happy face.",
    release_date: "2019-10-02",
    runtime: 122,
    status: "Released",
    budget: 55000000,
    revenue: 1074251311,
    overview: "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
    genres: [{ name: "Crime" }, { name: "Thriller" }, { name: "Drama" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Warner Bros. Pictures" }, { name: "DC Films" }]
  },
  {
    id: 29,
    title: 'Avengers: Endgame',
    poster_path: '/orSbi94p9p9p9p9p9p9p9p9p9p.jpg',
    vote_average: 8.3,
    tagline: "Avenge the fallen.",
    release_date: "2019-04-24",
    runtime: 181,
    status: "Released",
    budget: 356000000,
    revenue: 2797800564,
    overview: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to undo Thanos' actions and restore order to the universe.",
    genres: [{ name: "Action" }, { name: "Adventure" }, { name: "Science Fiction" }],
    spoken_languages: [{ name: "English" }, { name: "Japanese" }],
    production_companies: [{ name: "Marvel Studios" }]
  },
  {
    id: 30,
    title: 'The Dark Knight Rises',
    poster_path: '/vSbi94p9p9p9p9p9p9p9p9p9p.jpg',
    vote_average: 7.8,
    tagline: "The Legend Ends.",
    release_date: "2012-07-16",
    runtime: 165,
    status: "Released",
    budget: 250000000,
    revenue: 1081041287,
    overview: "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
    genres: [{ name: "Action" }, { name: "Crime" }, { name: "Drama" }, { name: "Thriller" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Warner Bros. Pictures" }, { name: "Legendary Pictures" }]
  },
  {
    id: 31,
    title: 'The Prestige',
    poster_path: '/bdN3g7vRMvS0NlnpT6Slo0C9p9p.jpg',
    vote_average: 8.2,
    tagline: "Are you watching closely?",
    release_date: "2006-10-19",
    runtime: 130,
    status: "Released",
    budget: 40000000,
    revenue: 109676311,
    overview: "A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy full of obsession, deceit and jealousy with dangerous and deadly consequences.",
    genres: [{ name: "Drama" }, { name: "Mystery" }, { name: "Thriller" }],
    spoken_languages: [{ name: "English" }],
    production_companies: [{ name: "Touchstone Pictures" }, { name: "Warner Bros. Pictures" }]
  },
  {
    id: 32,
    title: 'The Wolf of Wall Street',
    poster_path: '/p7m7m7m7m7m7m7m7m7m7m7m7m7m.jpg',
    vote_average: 8.0,
    tagline: "And then there was one.",
    release_date: "2013-12-25",
    runtime: 180,
    status: "Released",
    budget: 100000000,
    revenue: 392000694,
    overview: "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
    genres: [{ name: "Crime" }, { name: "Drama" }, { name: "Comedy" }],
    spoken_languages: [{ name: "English" }, { name: "French" }],
    production_companies: [{ name: "Appian Way" }, { name: "Sikelia Productions" }]
  }
];